language: node_js
os: linux
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
jobs:
  include:
    - node_js: "10.19.0"
      dist: trusty
      env:
        - CHROMIUM=true
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./travis/chromium.sh
